# Generated by Django 5.0.4 on 2024-05-05 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiluxe_app', '0002_alter_perfume_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfume',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
