# Generated by Django 5.0.4 on 2024-05-06 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiluxe_app', '0004_alter_perfume_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date_sent', models.DateField()),
            ],
        ),
    ]
