# Generated by Django 5.0.4 on 2024-05-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiluxe_app', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='liked_perfumes',
            field=models.ManyToManyField(related_name='liked_by', to='lumiluxe_app.perfume'),
        ),
    ]
