# Generated by Django 5.0.4 on 2024-05-06 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiluxe_app', '0007_perfume_likes_userprofile_liked_perfumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perfume_buy',
            field=models.URLField(blank=True),
        ),
    ]
