# Generated by Django 5.0.4 on 2024-05-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumiluxe_app', '0008_userprofile_perfume_buy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='perfume_buy',
        ),
        migrations.AddField(
            model_name='perfume',
            name='perfume_buy',
            field=models.URLField(blank=True),
        ),
    ]
